#!/usr/bin/env bash
# installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html

# testing nginx configuration
sudo nginx -t

sudo service nginx reload
