#!/bin/env bash

# Replace [STUDENT_ID] with your actual student ID
STUDENT_ID="222309"

# Update the package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 ${STUDENT_ID}-web-01 34.224.4.15:80 check
    server web-02 ${STUDENT_ID}-web-02 52.91.125.66:80 check
EOL

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

# Start HAProxy service
sudo systemctl start haproxy

